# Dead host (404) nginx config
{{#if enabled}}
server {
  listen 80;
  {{#eq disable_ipv6 false}}
  listen [::]:80;
  {{/eq}}

  {{#if has_certificate}}
  listen 443 ssl;
  {{#if http2_support}}
  http2 on;
  {{/if}}
  {{/if}}

  server_name {{#each domains}}{{this}} {{/each}};

  client_header_buffer_size 8k;
  large_client_header_buffers 4 32k;

  {{#if has_certificate}}
  {{#if is_letsencrypt}}
  ssl_certificate /etc/letsencrypt/live/npm-{{certificate_id}}/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/npm-{{certificate_id}}/privkey.pem;
  ssl_trusted_certificate /etc/letsencrypt/live/npm-{{certificate_id}}/chain.pem;
  include conf.d/include/ssl-ciphers.conf;
  ssl_stapling on;
  ssl_stapling_verify on;
  {{else}}
  ssl_certificate /data/custom_ssl/npm-{{certificate_id}}/fullchain.pem;
  ssl_certificate_key /data/custom_ssl/npm-{{certificate_id}}/privkey.pem;
  include conf.d/include/ssl-ciphers.conf;
  {{/if}}
  {{/if}}

  {{#if has_certificate}}
  {{#if ssl_forced}}
  if ($scheme = "http") {
    return 301 https://$host$request_uri;
  }
  {{/if}}
  {{#if hsts_enabled}}
  add_header Strict-Transport-Security "max-age=31536000;{{#if hsts_subdomains}} includeSubDomains;{{/if}} preload" always;
  {{/if}}
  {{/if}}

  access_log /data/logs/dead_host-{{id}}.log standard;

  {{advanced_config}}

  {{#if use_default_location}}
  location / {
    return 404;
  }
  {{/if}}
}
{{/if}}
