# Reverse proxy host nginx config
{{#if enabled}}
server {
  set $forward_scheme {{forward_scheme}};
  set $server         "{{forward_host}}";
  set $port           {{forward_port}};

  listen 80;
  {{#eq disable_ipv6 false}}
  listen [::]:80;
  {{/eq}}

  {{#if has_certificate}}
  listen 443 ssl;
  {{#if http2_support}}
  http2 on;
  {{/if}}
  {{/if}}

  server_name {{#each domains}}{{this}} {{/each}};

  client_header_buffer_size 8k;
  large_client_header_buffers 4 32k;
  proxy_buffer_size 32k;
  proxy_buffers 8 64k;

  {{#if has_certificate}}
  {{#if is_letsencrypt}}
  ssl_certificate /etc/letsencrypt/live/npm-{{certificate_id}}/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/npm-{{certificate_id}}/privkey.pem;
  ssl_trusted_certificate /etc/letsencrypt/live/npm-{{certificate_id}}/chain.pem;
  include conf.d/include/ssl-ciphers.conf;
  ssl_stapling on;
  ssl_stapling_verify on;
  {{else}}
  ssl_certificate /data/custom_ssl/npm-{{certificate_id}}/fullchain.pem;
  ssl_certificate_key /data/custom_ssl/npm-{{certificate_id}}/privkey.pem;
  include conf.d/include/ssl-ciphers.conf;
  {{/if}}
  {{/if}}

  {{#if caching_enabled}}
  include conf.d/include/assets.conf;
  {{/if}}

  {{#if block_exploits}}
  include conf.d/include/block-exploits.conf;
  {{/if}}

  {{#if has_certificate}}
  {{#if ssl_forced}}
  if ($scheme = "http") {
    return 301 https://$host$request_uri;
  }
  {{/if}}
  {{#if hsts_enabled}}
  add_header Strict-Transport-Security "max-age=31536000;{{#if hsts_subdomains}} includeSubDomains;{{/if}} preload" always;
  {{/if}}
  {{/if}}

  access_log /data/logs/proxy_host-{{id}}.log proxy;

  {{advanced_config}}

  {{#each locations}}
  location {{this.path}} {
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-Scheme $scheme;
    proxy_set_header X-Forwarded-Proto  $scheme;
    proxy_set_header X-Forwarded-For    $proxy_add_x_forwarded_for;
    proxy_pass       {{this.forward_scheme}}://{{this.forward_host}}:{{this.forward_port}};
    {{this.advanced_config}}
  }
  {{/each}}

  {{#if use_default_location}}
  location / {
    {{#if has_access_list}}
    auth_basic            "Authorization required";
    auth_basic_user_file  /data/access/{{access_list_id}}.htpasswd;
    {{/if}}

    {{#if allow_websocket_upgrade}}
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_http_version 1.1;
    {{/if}}

    {{#if trust_forwarded_proto}}
    proxy_set_header X-Forwarded-Proto $http_x_forwarded_proto;
    proxy_set_header X-Real-IP $remote_addr;
    {{/if}}

    include conf.d/include/proxy.conf;
  }
  {{/if}}

  include /data/nginx/custom/server_proxy[.]conf;
}
{{/if}}
