# TCP/UDP stream proxy nginx config
{{#if enabled}}
{{#if tcp_forwarding}}
server {
    listen {{incoming_port}};
    {{#eq disable_ipv6 false}}
    listen [::]:{{incoming_port}};
    {{/eq}}

    proxy_pass {{forward_ip}}:{{forwarding_port}};
    proxy_timeout 60s;
    proxy_connect_timeout 5s;
    access_log /data/logs/stream-{{id}}.log stream;

    {{advanced_config}}
}
{{/if}}

{{#if udp_forwarding}}
server {
    listen {{incoming_port}} udp;
    {{#eq disable_ipv6 false}}
    listen [::]:{{incoming_port}} udp;
    {{/eq}}

    proxy_pass {{forward_ip}}:{{forwarding_port}};
    proxy_timeout 60s;
    proxy_responses 1;
    access_log /data/logs/stream-{{id}}.log stream;

    {{advanced_config}}
}
{{/if}}
{{/if}}
