# HTTPS fallback when no matching SNI (before backend generates default_host/site.conf)

server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name _npm_fallback_;

    access_log /dev/null;
    error_log /dev/null warn;
    ssl_certificate /data/nginx/dummycert.pem;
    ssl_certificate_key /data/nginx/dummykey.pem;

    return 444;
}
