#!/bin/sh
set -e

# Nginx container entrypoint: init directories, generate configs, start watcher

echo "[nginx] Starting initialisation..."

mkdir -p /tmp/nginx/body \
    /run/nginx \
    /var/log/nginx \
    /data/nginx/default_host \
    /data/nginx/default_www \
    /data/nginx/proxy_host \
    /data/nginx/redirection_host \
    /data/nginx/stream \
    /data/nginx/dead_host \
    /data/nginx/temp \
    /data/nginx/custom \
    /data/custom_ssl \
    /data/logs \
    /data/access \
    /data/letsencrypt-acme-challenge \
    /var/lib/nginx/cache/public \
    /var/cache/nginx/proxy_temp

touch /var/log/nginx/error.log
chmod -R 755 /var/cache/nginx

echo "[nginx] Generating resolver config..."
RESOLVER_LINE=$(awk 'BEGIN{ORS=" "} $1=="nameserver" {print ($2 ~ ":")? "["$2"]": $2}' /etc/resolv.conf)
if [ -n "$RESOLVER_LINE" ]; then
    echo "resolver ${RESOLVER_LINE} valid=30s;" > /etc/nginx/conf.d/include/resolvers.conf
else
    echo "resolver 127.0.0.11 valid=30s;" > /etc/nginx/conf.d/include/resolvers.conf
fi

# Seed default include files
mkdir -p /etc/nginx/conf.d/include
if [ ! -f /etc/nginx/conf.d/include/ip_ranges.conf ]; then
    echo "# IP ranges — auto-generated by backend" > /etc/nginx/conf.d/include/ip_ranges.conf
fi

INCLUDE_SRC="/etc/nginx/conf.d/custom-origin/include"
if [ -d "$INCLUDE_SRC" ]; then
    for f in "$INCLUDE_SRC"/*.conf; do
        [ -f "$f" ] || continue
        fname=$(basename "$f")
        if [ ! -f "/etc/nginx/conf.d/include/$fname" ]; then
            cp "$f" "/etc/nginx/conf.d/include/$fname"
        fi
    done
fi

# Generate dummy SSL cert if missing
if [ ! -f /data/nginx/dummycert.pem ] || [ ! -f /data/nginx/dummykey.pem ]; then
    echo "[nginx] Generating dummy SSL certificate (ECDSA P-256)..."
    openssl ecparam -genkey -name prime256v1 -noout -out /data/nginx/dummykey.pem 2>/dev/null
    openssl req -new -days 3650 -nodes -x509 \
        -key /data/nginx/dummykey.pem \
        -subj '/O=Nginx Proxy Manager/OU=Dummy Certificate/CN=localhost' \
        -out /data/nginx/dummycert.pem
fi

# Copy default page into persistent volume if missing
if [ ! -f /data/nginx/default_www/index.html ] && [ -f /etc/nginx/default-index.html ]; then
    export APP_VERSION="$(cat /app/.version 2>/dev/null | tr -d '[:space:]')" || true
    envsubst '${APP_VERSION}' < /etc/nginx/default-index.html > /data/nginx/default_www/index.html
fi

rm -f /etc/letsencrypt/cli.ini

# Copy production/default configs if missing
ORIGIN_DIR="/etc/nginx/conf.d/custom-origin"
if [ ! -f /etc/nginx/conf.d/production.conf ] && [ -f "$ORIGIN_DIR/production.conf" ]; then
    cp "$ORIGIN_DIR/production.conf" /etc/nginx/conf.d/production.conf
fi
if [ ! -f /etc/nginx/conf.d/default.conf ] && [ -f "$ORIGIN_DIR/default.conf" ]; then
    cp "$ORIGIN_DIR/default.conf" /etc/nginx/conf.d/default.conf
fi

echo "[nginx] Initialisation complete!"

# Start inotify config watcher
DEBOUNCE_SEC=1
WATCH_DIRS="/data/nginx/proxy_host /data/nginx/redirection_host /data/nginx/dead_host /data/nginx/stream /data/nginx/default_host /data/nginx/temp /data/nginx/custom /etc/nginx/conf.d/include"

WATCHER_PID=""

start_config_watcher() {
    echo "[nginx-watcher] Starting config watcher (inotify)..."
    echo "[nginx-watcher] Watching: $WATCH_DIRS"
    while true; do
        CHANGE=$(inotifywait -q -r -e create,modify,delete,moved_to,moved_from \
            --include '\.conf$' \
            $WATCH_DIRS 2>/dev/null) || true
        if [ -z "$CHANGE" ]; then
            sleep 5
            continue
        fi
        sleep "$DEBOUNCE_SEC"
        echo "[nginx-watcher] Config change detected, validating..."
        if nginx -t 2>/dev/null; then
            nginx -s reload 2>/dev/null && echo "[nginx-watcher] Reload successful"
        else
            echo "[nginx-watcher] Config test failed — skipping reload"
        fi
    done
}

start_config_watcher &
WATCHER_PID=$!

# Graceful shutdown handler
shutdown() {
    echo "[nginx] Caught shutdown signal, stopping..."
    if [ -n "$WATCHER_PID" ] && kill -0 "$WATCHER_PID" 2>/dev/null; then
        kill "$WATCHER_PID" 2>/dev/null
        wait "$WATCHER_PID" 2>/dev/null
        echo "[nginx-watcher] Stopped"
    fi
    nginx -s quit 2>/dev/null
    exit 0
}

trap shutdown SIGTERM SIGINT

echo "[nginx] Starting nginx..."
exec nginx -g "daemon off;"
