user root;

worker_processes auto;
pid /tmp/nginx.pid;
error_log /dev/null warn;

events {
    worker_connections 1024;
}

http {
    include mime.types;
    default_type application/octet-stream;

    map $host $forward_scheme {
        default http;
    }
    map $host $server {
        default "";
    }
    map $host $port {
        default "";
    }

    include /data/nginx/*.conf;
}
