# ACME challenge handler
location ^~ /.well-known/acme-challenge/ {
    auth_basic off;
    allow all;
    default_type "text/plain";
    root /data/letsencrypt-acme-challenge;
}

location = /.well-known/acme-challenge/ {
    return 404;
}
